version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      # Checkout.
      - restore_cache:
          keys:
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      - checkout
      - save_cache:
          key: git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths: [".git"]
      # Install tools.
      - run: mix local.hex --force
      # Dependencies.
      - restore_cache:
          keys:
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "mix.lock" }}
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      - run: mix deps.get
      - save_cache:
          key: deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      # Build.
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      - run: mix deps.compile --include-children && mix compile
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths: ["_build"]


   credo:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: dev
    working_directory: ~/repo
    steps:
      # Checkout.
      - restore_cache:
          keys:
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      - checkout
      # Install tools.
      - run: mix local.hex --force
      # Dependencies.
      - restore_cache:
          keys:
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "mix.lock" }}
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      # Build.
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      ##
      ## Credo.
      ##
      - run: mix credo

  test:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      # Checkout.
      - restore_cache:
          keys:
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - git-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      - checkout
      # Install tools.
      - run: mix local.hex --force
      # Dependencies.
      - restore_cache:
          keys:
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ checksum "mix.lock" }}
            - deps-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      # Build.
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
            - build-cache-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
      ##
      ## Test.
      ##
      - run: mix test

workflows:
  version: 2
  build_verification:
      jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build

